config/routes.rb
Rails.application.routes.draw do
  devise_for :users

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end 
  
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create] do
        resources :posts, only: [:index, :show, :create] do
          resources :comments, only: [:index, :show, :create]
        end
      end
    end
  end
   # Defines the root path route ("/")
  root "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    user ||= User.new # guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all # admin can do everything
    else
      can :read, :all # everyone can read everything
      can :create, Comment # everyone can create comments
      can :create, Post # everyone can create comments
      can :destroy, Comment, author_id: user.id # users can delete their own comments
      can :destroy, Post, author_id: user.id # users can delete their own posts
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :text, presence: true, length: { maximum: 250 }

  after_save :update_comments_counter
  after_destroy :decrement_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end

  def decrement_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true, length: { maximum: 1000 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter
  after_destroy :decrement_posts_counter

  def five_most_recent_comments
    comments.last(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def decrement_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_posts
    posts.last(3)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    post = Post.find(params[:post_id])
    comments = post.comments

    if comments.size.positive?
      render json: comments, status: :ok
    else
      render json: { message: 'No comments found' }, status: :not_found
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(text: params[:text], author: current_user, post: @post)
    if @comment.save
      render json: @comment, status: :created
    else
      render json: { message: 'Comment not created', erors: @comment.errors.messages },
             status: :unprocessable_entity
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = user.posts.includes(:comments)

    if posts.size.positive?
      render json: posts, status: :ok
    else
      render json: { message: 'No posts found' }, status: :not_found
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end

  # To handle the POST request from the command line to the /api/v1/users/:id/posts/:post_id/comments.json
  def verified_request?
    super || request_from_localhost?
  end

  def request_from_localhost?
    request.remote_ip == '127.0.0.1' || request.remote_ip == '::1'
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, only: [:create]

  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment
    @comment.destroy
    redirect_to user_post_path(params[:user_id], params[:post_id]), notice: 'Comment was successfully deleted.'
  end

  def comment_params
    @post = Post.find_by(id: params[:post_id])
    params
      .require(:comment)
      .permit(:text)
      .merge(author: current_user, post: @post)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(author_id: current_user.id, post_id: @post.id)

    return unless @like.save

    redirect_to "/users/#{@post.author.id}/posts/#{@post.id}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, only: [:create]

  def index
    @user = User.includes(posts: :comments).find(params[:user_id])
  end

  def show
    @post = User.find(params[:user_id]).posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.destroy!
    redirect_to user_posts_path(current_user), notice: 'Post was successfully deleted.'
  end

  def post_params
    params
      .require(:post)
      .permit(:title, :text)
      .merge(author: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h2>Please, Add your comment</h2>

<div>
    <%= render 'shared/comment' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/_new_like.html.erb
<%= form_with url: "/users/#{@post.author.id}/posts/#{@post.id}/likes" do |f| %>
    <%= f.submit 'Like post' %>
<%end%>

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post do |f| %>

    <div>
      <div>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
      </div>
    
      <div>
        <%= f.label :text %><br>
        <%= f.text_area :text %>
      </div>
      <%= f.submit %> <br>
    </div>
    
    <% end %>

app/views/posts/index.html.erb
<div class="user_posts_container">
    <div class="user_post_section">
        <%= image_tag(@user.photo || '', class: "user_post_section_image") %>
        <div class="user_post_details_info">
            <h2 class="user_post_section_title"><%= @user.name %></h2>
            <span>Number of posts: <%= @user.posts.count %> </span>
        </div>
    </div>
    <div class="user_posts_main">
        <%- @user.posts.each do |post| -%>
           <div class="user_posts_info">
            <h3 class="user_post_title"><%= link_to post.title, user_post_path(post.author, post.id) %></h3>
                <p><%= post.text %></p>
                <div class="user_posts_comments_likes">
                    <span>Comments: <%= post.comments_counter %></span>
                    <span>Likes: <%= post.likes_counter %></span>
                </div>
                <a href="/users/<%= @user.id %>/posts/<%= post.id %>" class="">view post</a>
                <div>
                <% if can? :destroy, post %>
                    <%= button_to 'Delete post', user_post_path(post.author, post), method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
            </div>
            </div>
            <span class="top_comments">Top five comments</span>
            <div class="user_comments_info">
                <% post.five_most_recent_comments.each do |comment| %>
                    <div class="user_comment_div">
                        <span><%= comment.author.name  %>: </span>
                        <span><%= comment.text  %></span>
                    </div>
                    <div>
                    <% if can? :destroy, comment %>
                        <%= button_to 'Delete comment', user_post_comment_path(comment.author, post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                </div>
                <%-end-%>
            </div>
        <%-end-%>
    </div>
</div>

app/views/posts/new.html.erb
<h2>Create new Post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="post_section">
    <div class="post_info">
        <h3 class="post_title"><%= @post.title %> by <%= @post.author.name %></h3>
        <div class="post_comments_likes_count">
            <span>Comments: <%= @post.comments_counter %></span>
            <span>Likes: <%= @post.likes_counter %></span>
        </div>
        <p class="post_text"><%= @post.text %></p>
        <%= render 'likes/new_like', local: {post: @post} %>
        <div>
        <% if can? :destroy, @post %>
            <%= button_to 'Delete post', user_post_path(@post.author, @post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    </div>
    </div>
    <div class="post_comments">
        <% @post.comments.each do |comment| %>
            <div class="post_comments_details">
            <div>
            <span><%= comment.author.name  %>: </span>
            <span><%= comment.text  %></span>
        </div>
        <div>
            <% if can? :destroy, comment %>
                <%= button_to 'Delete comment', user_post_comment_path(comment.author, @post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </div>
            </div>
        <%-end-%>
    </div>
    <button><%= link_to  "Create new Comment", new_user_post_comment_path(@post.author, @post)  %></button>
</div>

app/views/shared/_comment.html.erb
<%= form_with model: @comments, url: user_post_comments_path, scope: :comment do |f| %>

    <div>
      <div>
        <%= f.label :text %><br>
        <%= f.text_area :text %>
      </div>
      <%= f.submit 'comment' %> <br>
    </div>
    
    <% end %>

app/views/users/_post.html.erb
<%- @user.three_most_recent_posts.each do |post| -%>
    <div class="user_details_post_container">
    <h3 class="user_details_post_title"><%= link_to post.title, user_post_path(post.author.id, post.id) %></h3>
        <p><%= post.text %></p>
        <div>
        <% if can? :destroy, post %>
            <%= button_to 'Delete post', user_post_path(post.author, post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    </div>
        <div class="user_comments_and_likes">
            <span>Comments: <%= post.comments_counter %></span>
            <span>Likes: <%= post.likes_counter %></span>
        </div>
    </div>
<%-end-%>

app/views/users/index.html.erb
<%-@users.each do |user|-%>
    <div class="user_main">
        <%= image_tag(user.photo || '', class: "user_image") %>
        <div class="user_details">
            <h2 class="user_title"><%= user.name %></h2>
            <span>Number of posts: <%= user.posts.count %> </span>
            <span><%= link_to 'view', user %></span>
        </div>
    </div>
<%-end-%>

app/views/users/show.html.erb
<div class="user_container">
 <div class="user_hero">
 <div class="user_section">
    <%= image_tag(@user.photo || '', class: "user_section_image") %>
    <div class="user_details_info">
        <h2 class="user_section_title"><%= @user.name %></h2>
        <span>Number of posts: <%= @user.posts.count %> </span>
    </div>
</div>
<div class="user_bio_section">
    <h3 class="user_bio_title">Bio</h3>
    <span>
        <%= @user.bio %>
    </span>
    <br>
    <div>
        <% if user_signed_in? && current_user.id == @user.id %>
            <%= link_to "Create Post", new_user_post_path(@user) %>
        <% end %>
    </div>
    </div>
    </div>

    <div class="user_details_post">
    <h3 class="recent_title">Users Top Recent Posts</h3>
        <%= render 'post', posts: @user.three_most_recent_posts %>
    </div>
    <a href="/users/<%= @user.id %>/posts" class="user_details_see_btn">See all posts</a>
    <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
</div>